import type { Unit } from "./types";

/** Sector 4 — Boolean Logic (syllabus 10; Paper 2). */
const U = "sector-4";

export const booleanLogic: Unit = {
  id: U,
  order: 4,
  syllabusRef: "10",
  paper: 2,
  title: "Boolean Logic",
  blurb: "Logic gates, truth tables, expressions and circuits.",
  sector: { number: 4, name: "Boolean Logic", boss: "The Gatekeeper" },
  isRewardSector: true,
  lessons: [
    {
      id: "s4-l1",
      unitId: U,
      topicCode: "10",
      title: "The six gates",
      summary: "NOT, AND, OR, NAND, NOR and XOR — and exactly when each outputs 1.",
      widgets: ["logic-playground"],
      cards: [
        {
          id: "s4-l1-c1",
          title: "What each gate does",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "NOT", v: "one input — inverts it (1→0, 0→1)." },
                { k: "AND", v: "output 1 only when ALL inputs are 1." },
                { k: "OR", v: "output 1 when AT LEAST ONE input is 1." },
                { k: "NAND", v: "NOT AND — output 0 only when all inputs are 1." },
                { k: "NOR", v: "NOT OR — output 1 only when all inputs are 0." },
                { k: "XOR", v: "output 1 only when the inputs are DIFFERENT." },
              ],
            },
            { kind: "widget", widget: "logic-playground", caption: "Build a circuit, toggle inputs, and read the live truth table." },
          ],
        },
        {
          id: "s4-l1-c2",
          title: "The classic traps",
          blocks: [
            {
              kind: "callout",
              tone: "mistake",
              title: "OR vs XOR",
              text: "**OR** is 1 if *any* input is 1 (including both). **XOR** is 1 only if the inputs *differ* — so 1 XOR 1 = 0.",
            },
            {
              kind: "callout",
              tone: "mistake",
              title: "NAND / NOR",
              text: "NAND = NOT(A AND B); NOR = NOT(A OR B). Do the AND/OR first, THEN invert.",
            },
          ],
        },
      ],
      recall: [
        { id: "s4-l1-r1", prompt: "When is XOR's output 1?", answer: "Only when the inputs are different." },
        { id: "s4-l1-r2", prompt: "What is 1 NAND 1?", answer: "0 (AND gives 1, then NOT makes it 0)." },
      ],
    },
    {
      id: "s4-l2",
      unitId: U,
      topicCode: "10",
      title: "Truth tables & expressions",
      summary: "Eight rows for three inputs, written in order — and reading them off.",
      widgets: ["truth-table-fill"],
      cards: [
        {
          id: "s4-l2-c1",
          title: "Completing a truth table",
          blocks: [
            {
              kind: "p",
              text: "For 3 inputs there are **8 rows** — list them in order from 000 to 111. Work the expression out for each row, one gate at a time (inner brackets first).",
            },
            { kind: "widget", widget: "truth-table-fill", caption: "Fill the output column — checked row by row." },
          ],
        },
        {
          id: "s4-l2-c2",
          title: "From problem to circuit",
          blocks: [
            {
              kind: "list",
              items: [
                "Read the problem and decide the condition for the output to be 1.",
                "Write it as a logic expression using AND / OR / NOT (and the other gates).",
                "Build the circuit (≤3 inputs, 1 output) — no simplification needed at IGCSE.",
              ],
            },
            {
              kind: "callout",
              tone: "info",
              text: "Example: 'output is 1 when A is on AND B is off' → `A AND (NOT B)`.",
            },
          ],
        },
      ],
      recall: [
        { id: "s4-l2-r1", prompt: "How many rows does a 3-input truth table have?", answer: "8 (2³)." },
        { id: "s4-l2-r2", prompt: "Write an expression for 'output 1 when A is 1 and B is 0'.", answer: "A AND (NOT B)." },
      ],
    },
  ],
  flashcards: [
    { id: "s4-f1", unitId: U, topicCode: "10", front: "AND outputs 1 when…?", back: "All inputs are 1." },
    { id: "s4-f2", unitId: U, topicCode: "10", front: "OR outputs 1 when…?", back: "At least one input is 1." },
    { id: "s4-f3", unitId: U, topicCode: "10", front: "XOR outputs 1 when…?", back: "The inputs are different." },
    { id: "s4-f4", unitId: U, topicCode: "10", front: "NAND is equivalent to…?", back: "NOT (A AND B)." },
    { id: "s4-f5", unitId: U, topicCode: "10", front: "NOR outputs 1 when…?", back: "All inputs are 0." },
    { id: "s4-f6", unitId: U, topicCode: "10", front: "Rows in a 3-input truth table?", back: "8 (list 000 → 111)." },
    { id: "s4-f7", unitId: U, topicCode: "10", front: "1 XOR 1 = ?", back: "0 (inputs are the same)." },
    { id: "s4-f8", unitId: U, topicCode: "10", front: "NOT 0 = ?", back: "1 (NOT inverts the input)." },
  ],
  drill: [
    {
      id: "s4-d1",
      unitId: U,
      topicCode: "10",
      type: "fill",
      difficulty: "core",
      prompt: "A=1, B=0. What is A AND B? (0 or 1)",
      explanation: "AND needs both inputs 1, so 1 AND 0 = 0.",
      answer: "0",
    },
    {
      id: "s4-d2",
      unitId: U,
      topicCode: "10",
      type: "fill",
      difficulty: "core",
      prompt: "A=1, B=1. What is A XOR B? (0 or 1)",
      explanation: "XOR is 1 only when inputs differ; they're the same, so 0.",
      answer: "0",
    },
    {
      id: "s4-d3",
      unitId: U,
      topicCode: "10",
      type: "mcq",
      difficulty: "core",
      prompt: "Which gate outputs 1 ONLY when the two inputs are different?",
      explanation: "That's XOR. OR would also be 1 when both inputs are 1.",
      choices: [
        { id: "a", text: "XOR" },
        { id: "b", text: "OR", misconception: "OR is also 1 when both inputs are 1 — XOR is not." },
      ],
      correctId: "a",
    },
    {
      id: "s4-d4",
      unitId: U,
      topicCode: "10",
      type: "fill",
      difficulty: "core",
      prompt: "A=0, B=0. What is A NOR B? (0 or 1)",
      explanation: "OR(0,0)=0, then NOT makes it 1.",
      answer: "1",
    },
  ],
  masteryTest: {
    passThreshold: 0.8,
    interleaveFromEarlier: 2,
    questions: [
      {
        id: "s4-t1",
        unitId: U,
        topicCode: "10",
        type: "fill",
        difficulty: "core",
        commandWord: "Calculate",
        prompt: "A=1, B=0. Output of A AND B? (0 or 1)",
        explanation: "AND needs all inputs 1: 1 AND 0 = 0.",
        answer: "0",
      },
      {
        id: "s4-t2",
        unitId: U,
        topicCode: "10",
        type: "fill",
        difficulty: "core",
        commandWord: "Calculate",
        prompt: "A=1, B=0. Output of A OR B? (0 or 1)",
        explanation: "OR is 1 if any input is 1: 1 OR 0 = 1.",
        answer: "1",
      },
      {
        id: "s4-t3",
        unitId: U,
        topicCode: "10",
        type: "fill",
        difficulty: "core",
        commandWord: "Calculate",
        prompt: "A=1, B=1. Output of A XOR B? (0 or 1)",
        explanation: "XOR is 1 only when inputs differ; here they're equal, so 0.",
        answer: "0",
      },
      {
        id: "s4-t4",
        unitId: U,
        topicCode: "10",
        type: "mcq",
        difficulty: "core",
        prompt: "XOR outputs 1 when…",
        explanation: "XOR is 1 only when the inputs are different.",
        choices: [
          { id: "a", text: "the two inputs are different" },
          { id: "b", text: "at least one input is 1", misconception: "that describes OR, which is also 1 when both are 1." },
        ],
        correctId: "a",
      },
      {
        id: "s4-t5",
        unitId: U,
        topicCode: "10",
        type: "mcq",
        difficulty: "core",
        prompt: "NAND is equivalent to…",
        explanation: "NAND = NOT(A AND B): do AND first, then invert.",
        choices: [
          { id: "a", text: "NOT (A AND B)" },
          { id: "b", text: "NOT A AND NOT B", misconception: "invert the result of AND, not each input." },
        ],
        correctId: "a",
      },
      {
        id: "s4-t6",
        unitId: U,
        topicCode: "10",
        type: "fill",
        difficulty: "core",
        commandWord: "Calculate",
        prompt: "A=0, B=0. Output of A NOR B? (0 or 1)",
        explanation: "OR(0,0)=0, NOT makes it 1.",
        answer: "1",
      },
      {
        id: "s4-t7",
        unitId: U,
        topicCode: "10",
        type: "fill",
        difficulty: "core",
        prompt: "What is NOT 1? (0 or 1)",
        explanation: "NOT inverts: NOT 1 = 0.",
        answer: "0",
      },
      {
        id: "s4-t8",
        unitId: U,
        topicCode: "10",
        type: "mcq",
        difficulty: "core",
        prompt: "Which gate outputs 1 ONLY when all inputs are 1?",
        explanation: "AND is 1 only when every input is 1.",
        choices: [
          { id: "a", text: "AND" },
          { id: "b", text: "OR", misconception: "OR is 1 if any input is 1, not only when all are." },
          { id: "c", text: "NAND", misconception: "NAND is 0 (not 1) when all inputs are 1." },
        ],
        correctId: "a",
      },
      {
        id: "s4-t9",
        unitId: U,
        topicCode: "10",
        type: "mcq",
        difficulty: "stretch",
        prompt: "Which gate outputs 0 ONLY when all inputs are 1?",
        explanation: "NAND = NOT AND, so it's 0 only when AND would be 1.",
        choices: [
          { id: "a", text: "NAND" },
          { id: "b", text: "NOR", misconception: "NOR is 1 only when all inputs are 0." },
        ],
        correctId: "a",
      },
      {
        id: "s4-t10",
        unitId: U,
        topicCode: "10",
        type: "fill",
        difficulty: "stretch",
        commandWord: "Calculate",
        prompt: "For A AND (B OR C), with A=1, B=0, C=1, the output is? (0 or 1)",
        explanation: "B OR C = 0 OR 1 = 1; A AND 1 = 1.",
        answer: "1",
      },
      {
        id: "s4-t11",
        unitId: U,
        topicCode: "10",
        type: "truefalse",
        difficulty: "core",
        prompt: "OR and XOR always give the same output for the same inputs.",
        explanation: "No — they differ when both inputs are 1 (OR=1, XOR=0).",
        answer: false,
      },
      {
        id: "s4-t12",
        unitId: U,
        topicCode: "10",
        type: "mcq",
        difficulty: "core",
        commandWord: "State",
        prompt: "How many rows are in a truth table with 3 inputs?",
        explanation: "2³ = 8 rows.",
        choices: [
          { id: "a", text: "8" },
          { id: "b", text: "6", misconception: "it's 2 to the power of the number of inputs, not 2×3." },
          { id: "c", text: "3", misconception: "that's the number of inputs, not the rows." },
        ],
        correctId: "a",
      },
      {
        id: "s4-t13",
        unitId: U,
        topicCode: "10",
        type: "mcq",
        difficulty: "stretch",
        commandWord: "Suggest",
        prompt: "Output is 1 only when A is on AND B is off. Best expression?",
        explanation: "A is 1 and B is 0 → A AND (NOT B).",
        choices: [
          { id: "a", text: "A AND (NOT B)" },
          { id: "b", text: "A AND B", misconception: "that needs B on too; we want B off." },
          { id: "c", text: "A OR (NOT B)", misconception: "OR would also be 1 when A is off; we need both conditions." },
        ],
        correctId: "a",
      },
    ],
  },
  tutor: {
    conceptSummary:
      "Sector 4 covers Boolean logic: the gates NOT (inverts), AND (1 only if all inputs 1), OR (1 if any input 1), NAND (NOT AND), NOR (NOT OR, 1 only if all inputs 0) and XOR (1 only if inputs differ). It covers completing a truth table for up to 3 inputs (8 rows, 000→111, inner brackets first), writing a logic expression from a problem or truth table, and building a circuit (≤3 inputs, 1 output, no simplification).",
    misconceptions: [
      "Confusing OR (1 if any input is 1, including both) with XOR (1 only if inputs differ).",
      "Treating NAND/NOR as inverting each input instead of inverting the AND/OR result.",
      "Truth-table row errors — not listing all 8 rows for 3 inputs in order.",
      "Flipping the NOT gate's output.",
    ],
  },
};
