import type { Unit } from "./types";

/**
 * Sector 1 — Data Representation (syllabus 1.1–1.3). Full build: six lessons
 * with embedded interactive widgets, expanded drills, and a 17-question boss
 * whose distractors are drawn from the common-mistakes list.
 */
const U = "sector-1";

export const dataRepresentation: Unit = {
  id: U,
  order: 1,
  syllabusRef: "1.1–1.3",
  paper: 1,
  title: "Data Representation",
  blurb: "Binary, hex, negatives, text, sound, images, storage & compression.",
  sector: { number: 1, name: "Data Representation", boss: "The Binary Hydra" },
  isRewardSector: true,
  lessons: [
    {
      id: "s1-l1",
      unitId: U,
      topicCode: "1.1",
      title: "Number systems",
      summary: "Denary, binary and hexadecimal — convert in every direction.",
      widgets: ["base-converter"],
      cards: [
        {
          id: "s1-l1-c1",
          title: "Three ways to write a number",
          blocks: [
            {
              kind: "list",
              items: [
                "**Denary** (base 10): the everyday system, digits 0–9.",
                "**Binary** (base 2): digits 0–1. How computers store everything. Each digit is a **bit**.",
                "**Hexadecimal** (base 16): digits 0–9 then A–F. A compact way to write binary — one hex digit = exactly 4 bits (a nibble).",
              ],
            },
            {
              kind: "callout",
              tone: "key",
              text: "Binary place values double each step: **128 64 32 16 8 4 2 1**. Add the places with a 1 to get the denary value.",
            },
          ],
        },
        {
          id: "s1-l1-c2",
          title: "Convert it live",
          blocks: [
            { kind: "p", text: "Toggle bits, or type a denary or hex value — watch all three stay in sync." },
            { kind: "widget", widget: "base-converter", caption: "Denary ⇄ binary ⇄ hex, with place values." },
            {
              kind: "p",
              text: "To go denary → binary, subtract the biggest place value you can, repeatedly. To go binary → hex, split into nibbles of 4 bits and convert each.",
            },
          ],
        },
      ],
      recall: [
        { id: "s1-l1-r1", prompt: "How many bits does one hex digit represent?", answer: "4 bits (a nibble)." },
        { id: "s1-l1-r2", prompt: "What is binary 1101 0010 in denary?", answer: "210 (128+64+16+2)." },
      ],
    },
    {
      id: "s1-l2",
      unitId: U,
      topicCode: "1.1",
      title: "Negatives, overflow & shifts",
      summary: "Two's complement, 8-bit addition, overflow, and logical shifts.",
      widgets: ["twos-complement", "binary-adder", "binary-shifter"],
      cards: [
        {
          id: "s1-l2-c1",
          title: "Two's complement — the sign bit",
          blocks: [
            {
              kind: "p",
              text: "To store negative integers, the most-significant bit becomes a **sign bit** worth **−128** (for 8 bits). If it's 1, the number is negative.",
            },
            { kind: "widget", widget: "twos-complement", caption: "The left bit is worth −128." },
            {
              kind: "callout",
              tone: "mistake",
              title: "Common slip",
              text: "Forgetting the sign bit. `10000000` is **−128**, not 128.",
            },
          ],
        },
        {
          id: "s1-l2-c2",
          title: "8-bit addition & overflow",
          blocks: [
            {
              kind: "p",
              text: "Add binary like denary, carrying 1 when a column makes 2. **Overflow** happens when the result needs more than the register's bits — an 8-bit register overflows above **255**.",
            },
            { kind: "widget", widget: "binary-adder", caption: "Carries shown in amber; the overflow flag lights up." },
          ],
        },
        {
          id: "s1-l2-c3",
          title: "Logical shifts",
          blocks: [
            {
              kind: "p",
              text: "A **logical shift left** multiplies by 2; a **shift right** divides by 2. Zeros fill the vacated end, and bits pushed off the end are **lost**.",
            },
            { kind: "widget", widget: "binary-shifter", caption: "Shift and watch ×2 / ÷2 — and the bit that falls off." },
          ],
        },
      ],
      recall: [
        { id: "s1-l2-r1", prompt: "In 8-bit two's complement, what is 1111 1111?", answer: "−1." },
        { id: "s1-l2-r2", prompt: "A left shift by 1 has what effect on the value (if nothing is lost)?", answer: "It multiplies by 2." },
      ],
    },
    {
      id: "s1-l3",
      unitId: U,
      topicCode: "1.2",
      title: "Text: ASCII & Unicode",
      summary: "How characters become binary — and the cost of more characters.",
      widgets: [],
      cards: [
        {
          id: "s1-l3-c1",
          title: "Character sets",
          blocks: [
            {
              kind: "p",
              text: "Every character is stored as a binary number via a **character set** — a lookup table from character to code.",
            },
            {
              kind: "kv",
              rows: [
                { k: "ASCII", v: "fewer bits per character; a limited set (English letters, digits, symbols)." },
                { k: "Unicode", v: "more bits per character; a huge set — many languages and emoji 😀." },
              ],
            },
            {
              kind: "callout",
              tone: "info",
              text: "Trade-off: Unicode represents far more characters, but each one takes more storage than ASCII.",
            },
          ],
        },
      ],
      recall: [
        { id: "s1-l3-r1", prompt: "Which uses more bits per character, ASCII or Unicode?", answer: "Unicode." },
        { id: "s1-l3-r2", prompt: "Why might a document use Unicode instead of ASCII?", answer: "To include characters ASCII can't — other languages, emoji, etc." },
      ],
    },
    {
      id: "s1-l4",
      unitId: U,
      topicCode: "1.2",
      title: "Sound",
      summary: "Sampling a wave: rate vs resolution, accuracy vs file size.",
      widgets: ["sound-sampler"],
      cards: [
        {
          id: "s1-l4-c1",
          title: "Sampling a sound wave",
          blocks: [
            {
              kind: "p",
              text: "A sound wave is **sampled** — measured at regular intervals — to digitise it.",
            },
            {
              kind: "kv",
              rows: [
                { k: "Sample rate", v: "samples per second (how often you measure)." },
                { k: "Sample resolution", v: "bits per sample (how precisely you measure each one)." },
              ],
            },
            { kind: "widget", widget: "sound-sampler", caption: "Drag the sliders — more rate/resolution → closer to the real wave, bigger file." },
            {
              kind: "callout",
              tone: "mistake",
              title: "Don't swap these",
              text: "Rate = samples per second. Resolution = bits per sample. Mixing them up is the classic exam slip.",
            },
          ],
        },
      ],
      recall: [
        { id: "s1-l4-r1", prompt: "What does a higher sample rate do to accuracy and file size?", answer: "Both increase — more accurate, larger file." },
        { id: "s1-l4-r2", prompt: "Sample resolution is measured in…?", answer: "Bits per sample." },
      ],
    },
    {
      id: "s1-l5",
      unitId: U,
      topicCode: "1.2",
      title: "Images",
      summary: "Pixels, resolution and colour depth.",
      widgets: ["pixel-builder"],
      cards: [
        {
          id: "s1-l5-c1",
          title: "Pixels make pictures",
          blocks: [
            {
              kind: "p",
              text: "A bitmap image is a grid of **pixels**. **Resolution** is the number of pixels; **colour depth** is the number of bits per pixel.",
            },
            { kind: "widget", widget: "pixel-builder", caption: "More colour depth = more colours per pixel = a bigger file." },
            {
              kind: "callout",
              tone: "mistake",
              title: "Resolution ≠ colour depth",
              text: "Resolution = how many pixels. Colour depth = bits per pixel. They're different dials.",
            },
          ],
        },
      ],
      recall: [
        { id: "s1-l5-r1", prompt: "What does colour depth measure?", answer: "Bits per pixel." },
        { id: "s1-l5-r2", prompt: "How many colours can a 4-bit colour depth show?", answer: "16 (2⁴)." },
      ],
    },
    {
      id: "s1-l6",
      unitId: U,
      topicCode: "1.3",
      title: "Storage & compression",
      summary: "×1024 units, file-size calculations, lossy vs lossless.",
      widgets: [],
      cards: [
        {
          id: "s1-l6-c1",
          title: "Units step by ×1024",
          blocks: [
            {
              kind: "p",
              text: "bit → nibble → byte → KiB → MiB → GiB → TiB → PiB → EiB. From the byte up, **each step is ×1024 (not 1000)**.",
            },
            {
              kind: "kv",
              rows: [
                { k: "1 byte", v: "8 bits" },
                { k: "1 KiB", v: "1024 bytes" },
                { k: "1 MiB", v: "1024 KiB" },
              ],
            },
          ],
        },
        {
          id: "s1-l6-c2",
          title: "File-size formulas",
          blocks: [
            {
              kind: "list",
              items: [
                "**Image** size (bits) = resolution (pixels) × colour depth (bits).",
                "**Sound** size (bits) = sample rate × sample resolution × seconds.",
                "Divide bits by 8 for bytes, then by 1024 for KiB.",
              ],
            },
          ],
        },
        {
          id: "s1-l6-c3",
          title: "Lossy vs lossless",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Lossy", v: "permanently discards data (e.g. lower resolution/sample rate). Smaller, not reversible." },
                { k: "Lossless", v: "keeps all data and is reversible (e.g. run-length encoding, RLE)." },
              ],
            },
            {
              kind: "callout",
              tone: "key",
              text: "Lossless **can** still shrink a file — RLE replaces runs like `WWWWW` with `5W`. Benefits of compression: less storage, less bandwidth, faster transmission.",
            },
          ],
        },
      ],
      recall: [
        { id: "s1-l6-r1", prompt: "How many bytes are in 1 KiB?", answer: "1024 (not 1000)." },
        { id: "s1-l6-r2", prompt: "Which compression is reversible — lossy or lossless?", answer: "Lossless." },
      ],
    },
  ],
  flashcards: [
    { id: "s1-f1", unitId: U, topicCode: "1.1", front: "Base of hexadecimal?", back: "16 (digits 0–9, A–F)." },
    { id: "s1-f2", unitId: U, topicCode: "1.1", front: "8-bit binary place values?", back: "128 64 32 16 8 4 2 1." },
    { id: "s1-f3", unitId: U, topicCode: "1.1", front: "Largest value in an 8-bit register?", back: "255 (256 values, 0–255)." },
    { id: "s1-f4", unitId: U, topicCode: "1.1", front: "In two's complement, the MSB is worth…?", back: "−128 (it's the sign bit)." },
    { id: "s1-f5", unitId: U, topicCode: "1.1", front: "Logical shift left by 1 does what?", back: "Multiplies by 2 (right = ÷2)." },
    { id: "s1-f6", unitId: U, topicCode: "1.2", front: "ASCII vs Unicode?", back: "ASCII: fewer bits, limited set. Unicode: more bits, far more characters." },
    { id: "s1-f7", unitId: U, topicCode: "1.2", front: "Sample rate vs sample resolution?", back: "Rate = samples/second; resolution = bits/sample." },
    { id: "s1-f8", unitId: U, topicCode: "1.2", front: "Image resolution vs colour depth?", back: "Resolution = number of pixels; colour depth = bits/pixel." },
    { id: "s1-f9", unitId: U, topicCode: "1.3", front: "1 KiB = ? bytes", back: "1024 bytes (×1024, not 1000)." },
    { id: "s1-f10", unitId: U, topicCode: "1.3", front: "Image file size formula?", back: "Resolution × colour depth (in bits)." },
    { id: "s1-f11", unitId: U, topicCode: "1.3", front: "Sound file size formula?", back: "Sample rate × resolution × seconds (in bits)." },
    { id: "s1-f12", unitId: U, topicCode: "1.3", front: "Lossy vs lossless?", back: "Lossy discards data; lossless keeps it all and is reversible (e.g. RLE)." },
  ],
  drill: [
    {
      id: "s1-d1",
      unitId: U,
      topicCode: "1.1",
      type: "numeric",
      difficulty: "core",
      prompt: "Convert binary 1101 0010 to denary.",
      explanation: "128+64+16+2 = 210.",
      answer: 210,
    },
    {
      id: "s1-d2",
      unitId: U,
      topicCode: "1.1",
      type: "fill",
      difficulty: "core",
      prompt: "Convert denary 47 to hexadecimal.",
      explanation: "47 = 2×16 + 15 = 2F.",
      answer: "2F",
      accept: ["0x2F"],
    },
    {
      id: "s1-d3",
      unitId: U,
      topicCode: "1.1",
      type: "mcq",
      difficulty: "core",
      prompt: "What is 1000 0000 in 8-bit two's complement?",
      explanation: "The sign bit (−128) is set and nothing else: −128.",
      choices: [
        { id: "a", text: "−128" },
        { id: "b", text: "128", misconception: "the MSB is the sign bit worth −128, not +128." },
        { id: "c", text: "0", misconception: "only the sign bit is set, so the value is −128." },
      ],
      correctId: "a",
    },
    {
      id: "s1-d4",
      unitId: U,
      topicCode: "1.2",
      type: "mcq",
      difficulty: "core",
      prompt: "Sample resolution is measured in…",
      explanation: "Resolution = bits per sample. Samples per second is the sample rate.",
      choices: [
        { id: "a", text: "bits per sample" },
        { id: "b", text: "samples per second", misconception: "that's the sample rate, not the resolution." },
      ],
      correctId: "a",
    },
    {
      id: "s1-d5",
      unitId: U,
      topicCode: "1.3",
      type: "numeric",
      difficulty: "core",
      prompt: "An image is 10×10 pixels at 4 bits per pixel. Size in bits?",
      explanation: "100 pixels × 4 bits = 400 bits.",
      answer: 400,
      unit: "bits",
    },
    {
      id: "s1-d6",
      unitId: U,
      topicCode: "1.3",
      type: "truefalse",
      difficulty: "core",
      prompt: "Lossless compression can still make a file smaller.",
      explanation: "Yes — RLE shrinks data with no loss and is reversible.",
      answer: true,
    },
    {
      id: "s1-d7",
      unitId: U,
      topicCode: "1.1",
      type: "truefalse",
      difficulty: "core",
      prompt: "Adding 200 + 100 in an 8-bit register causes overflow.",
      explanation: "300 > 255, so it overflows an 8-bit register.",
      answer: true,
    },
  ],
  masteryTest: {
    passThreshold: 0.8,
    interleaveFromEarlier: 0,
    questions: [
      {
        id: "s1-t1",
        unitId: U,
        topicCode: "1.1",
        type: "fill",
        difficulty: "core",
        commandWord: "Calculate",
        prompt: "Convert denary 200 to 8-bit binary.",
        explanation: "200 = 128+64+8 = 1100 1000.",
        answer: "11001000",
        accept: ["1100 1000"],
      },
      {
        id: "s1-t2",
        unitId: U,
        topicCode: "1.1",
        type: "numeric",
        difficulty: "core",
        commandWord: "Calculate",
        prompt: "Convert binary 1100 1000 to denary.",
        explanation: "128+64+8 = 200.",
        answer: 200,
      },
      {
        id: "s1-t3",
        unitId: U,
        topicCode: "1.1",
        type: "fill",
        difficulty: "stretch",
        commandWord: "Calculate",
        prompt: "Convert denary 60 to hexadecimal.",
        explanation: "60 = 3×16 + 12 = 3C.",
        answer: "3C",
        accept: ["0x3C"],
      },
      {
        id: "s1-t4",
        unitId: U,
        topicCode: "1.1",
        type: "numeric",
        difficulty: "stretch",
        commandWord: "Calculate",
        prompt: "Convert hexadecimal 2F to denary.",
        explanation: "2×16 + 15 = 47.",
        answer: 47,
        base: 16,
      },
      {
        id: "s1-t5",
        unitId: U,
        topicCode: "1.1",
        type: "mcq",
        difficulty: "core",
        prompt: "What is the largest value an 8-bit register can store?",
        explanation: "8 bits give 256 values, 0–255 — so the maximum is 255.",
        choices: [
          { id: "a", text: "255" },
          { id: "b", text: "256", misconception: "there are 256 values, but they run 0–255 — the max is 255." },
          { id: "c", text: "128", misconception: "128 is just the value of the most-significant bit." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t6",
        unitId: U,
        topicCode: "1.1",
        type: "mcq",
        difficulty: "stretch",
        prompt: "In 8-bit two's complement, what does 1000 0000 represent?",
        explanation: "Only the sign bit (−128) is set: the value is −128.",
        choices: [
          { id: "a", text: "−128" },
          { id: "b", text: "128", misconception: "you forgot the MSB is the sign bit, worth −128." },
          { id: "c", text: "−0", misconception: "two's complement has no negative zero; this is −128." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t7",
        unitId: U,
        topicCode: "1.1",
        type: "mcq",
        difficulty: "core",
        prompt: "A logical shift left by one place…",
        explanation: "Shifting left multiplies the value by 2 (right divides by 2).",
        choices: [
          { id: "a", text: "multiplies the value by 2" },
          { id: "b", text: "divides the value by 2", misconception: "that's a shift right; left multiplies." },
          { id: "c", text: "adds 1 to the value", misconception: "shifting isn't adding — left shift doubles." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t8",
        unitId: U,
        topicCode: "1.1",
        type: "truefalse",
        difficulty: "core",
        prompt: "Adding 180 + 120 in an 8-bit register causes overflow.",
        explanation: "300 > 255, so it overflows an 8-bit register.",
        answer: true,
      },
      {
        id: "s1-t9",
        unitId: U,
        topicCode: "1.2",
        type: "mcq",
        difficulty: "core",
        commandWord: "Identify",
        prompt: "Which character set uses MORE bits per character but covers far more characters?",
        explanation: "Unicode uses more bits than ASCII, covering many languages and emoji.",
        choices: [
          { id: "a", text: "Unicode" },
          { id: "b", text: "ASCII", misconception: "ASCII uses fewer bits and covers only a limited set." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t10",
        unitId: U,
        topicCode: "1.2",
        type: "mcq",
        difficulty: "core",
        prompt: "Sample rate is measured in…",
        explanation: "Rate = samples per second. Bits per sample is the resolution.",
        choices: [
          { id: "a", text: "samples per second" },
          { id: "b", text: "bits per sample", misconception: "that's sample resolution, not rate." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t11",
        unitId: U,
        topicCode: "1.2",
        type: "mcq",
        difficulty: "core",
        prompt: "What does an image's resolution measure?",
        explanation: "Resolution = the number of pixels. Bits per pixel is the colour depth.",
        choices: [
          { id: "a", text: "the number of pixels" },
          { id: "b", text: "the bits per pixel", misconception: "that's colour depth, not resolution." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t12",
        unitId: U,
        topicCode: "1.2",
        type: "truefalse",
        difficulty: "core",
        prompt: "Increasing the colour depth increases the file size.",
        explanation: "More bits per pixel → more colours and a larger file.",
        answer: true,
      },
      {
        id: "s1-t13",
        unitId: U,
        topicCode: "1.3",
        type: "mcq",
        difficulty: "core",
        commandWord: "State",
        prompt: "How many bytes are in 1 KiB?",
        explanation: "Storage units step by 1024, so 1 KiB = 1024 bytes.",
        choices: [
          { id: "a", text: "1024" },
          { id: "b", text: "1000", misconception: "storage uses ×1024, not ×1000." },
          { id: "c", text: "8", misconception: "8 is bits per byte, not bytes per KiB." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t14",
        unitId: U,
        topicCode: "1.3",
        type: "numeric",
        difficulty: "stretch",
        commandWord: "Calculate",
        prompt: "A 2-second clip is sampled 8000 times per second at 8 bits per sample. Size in bits?",
        explanation: "8000 × 8 × 2 = 128 000 bits.",
        answer: 128000,
        unit: "bits",
      },
      {
        id: "s1-t15",
        unitId: U,
        topicCode: "1.3",
        type: "mcq",
        difficulty: "core",
        prompt: "Which type of compression keeps ALL the original data and is reversible?",
        explanation: "Lossless keeps every bit and can be reversed; lossy permanently discards data.",
        choices: [
          { id: "a", text: "Lossless" },
          { id: "b", text: "Lossy", misconception: "lossy permanently discards data — it's not reversible." },
        ],
        correctId: "a",
      },
      {
        id: "s1-t16",
        unitId: U,
        topicCode: "1.3",
        type: "multi",
        difficulty: "stretch",
        commandWord: "Identify",
        prompt: "Select the LOSSLESS techniques.",
        explanation: "RLE is lossless and reversible. Lowering resolution or sample rate permanently discards data (lossy).",
        choices: [
          { id: "rle", text: "Run-length encoding (RLE)" },
          { id: "res", text: "Reducing the image resolution", misconception: "discarding pixels is lossy — data is lost." },
          { id: "rate", text: "Lowering the sample rate", misconception: "fewer samples means lost data — that's lossy." },
        ],
        correctIds: ["rle"],
      },
      {
        id: "s1-t17",
        unitId: U,
        topicCode: "1.3",
        type: "order",
        difficulty: "core",
        prompt: "Put these storage units in order, smallest first.",
        explanation: "bit (1) → nibble (4 bits) → byte (8 bits) → KiB (1024 bytes) → MiB (1024 KiB).",
        items: [
          { id: "kib", text: "KiB" },
          { id: "byte", text: "byte" },
          { id: "bit", text: "bit" },
          { id: "mib", text: "MiB" },
          { id: "nibble", text: "nibble" },
        ],
        correctOrder: ["bit", "nibble", "byte", "kib", "mib"],
      },
    ],
  },
  tutor: {
    conceptSummary:
      "Sector 1 covers number systems (denary/binary/hex conversions, two's complement with the −128 sign bit, 8-bit addition + overflow above 255, logical shifts where left=×2/right=÷2), text (ASCII fewer bits/limited vs Unicode more bits/more characters), sound (sample rate = samples/sec vs sample resolution = bits/sample; higher = more accurate + bigger), images (resolution = pixels vs colour depth = bits/pixel), and storage/compression (units ×1024, image size = resolution × colour depth, sound size = rate × resolution × seconds, lossy discards data vs lossless reversible e.g. RLE).",
    misconceptions: [
      "Swapping sample rate (samples/sec) with sample resolution (bits/sample).",
      "Swapping image resolution (number of pixels) with colour depth (bits/pixel).",
      "Using 1000 instead of 1024 between storage units.",
      "Thinking lossless compression can't reduce file size.",
      "Forgetting the sign bit in two's complement (1000 0000 is −128, not 128).",
      "Thinking an 8-bit register can hold 256 (the max value is 255).",
    ],
  },
};
