import type { Unit } from "./types";

/** Sector 3 — Hardware (syllabus 3.1–3.3). */
const U = "sector-3";

export const hardware: Unit = {
  id: U,
  order: 3,
  syllabusRef: "3.1–3.3",
  paper: 1,
  title: "Hardware",
  blurb: "The CPU, the fetch–decode–execute cycle, I/O, sensors & storage.",
  sector: { number: 3, name: "Hardware", boss: "The Von Neumann Core" },
  isRewardSector: true,
  lessons: [
    {
      id: "s3-l1",
      unitId: U,
      topicCode: "3.1",
      title: "The CPU & Von Neumann",
      summary: "The units, registers and buses inside the processor.",
      widgets: ["von-neumann-builder"],
      cards: [
        {
          id: "s3-l1-c1",
          title: "Inside the CPU",
          blocks: [
            {
              kind: "p",
              text: "The **CPU** processes instructions and data. A **microprocessor** is a CPU on a single chip. The **Von Neumann** model stores instructions and data together in memory.",
            },
            {
              kind: "kv",
              rows: [
                { k: "CU", v: "Control Unit — decodes instructions, coordinates everything." },
                { k: "ALU", v: "Arithmetic Logic Unit — calculations and logic." },
                { k: "Buses", v: "Address (where), Data (what), Control (signals)." },
              ],
            },
            { kind: "widget", widget: "von-neumann-builder", caption: "Tap each part to learn its role." },
          ],
        },
        {
          id: "s3-l1-c2",
          title: "The registers",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "PC", v: "Program Counter — address of the NEXT instruction." },
                { k: "MAR", v: "Memory Address Register — address being accessed now." },
                { k: "MDR", v: "Memory Data Register — data/instruction just fetched." },
                { k: "CIR", v: "Current Instruction Register — instruction being decoded." },
                { k: "ACC", v: "Accumulator — result of ALU calculations." },
              ],
            },
            {
              kind: "callout",
              tone: "mistake",
              title: "PC ≠ ACC",
              text: "The **PC** holds the next instruction's *address*; the **ACC** holds calculation *results*. Don't swap their jobs.",
            },
          ],
        },
      ],
      recall: [
        { id: "s3-l1-r1", prompt: "Which register holds the address of the next instruction?", answer: "The Program Counter (PC)." },
        { id: "s3-l1-r2", prompt: "What does the ALU do?", answer: "Arithmetic and logic operations (calculations and comparisons)." },
      ],
    },
    {
      id: "s3-l2",
      unitId: U,
      topicCode: "3.1",
      title: "Fetch–Decode–Execute & performance",
      summary: "The cycle the CPU repeats, and what makes it fast.",
      widgets: ["fde-cycle"],
      cards: [
        {
          id: "s3-l2-c1",
          title: "The FDE cycle",
          blocks: [
            {
              kind: "p",
              text: "The CPU repeats: **fetch** the next instruction from memory, **decode** it, then **execute** it. Step through it and watch each register and bus do its job.",
            },
            { kind: "widget", widget: "fde-cycle", caption: "Step the cycle — registers and buses light up." },
          ],
        },
        {
          id: "s3-l2-c2",
          title: "What affects performance",
          blocks: [
            {
              kind: "list",
              items: [
                "**Clock speed** — cycles per second; faster usually means more instructions per second.",
                "**Cores** — more cores can run more instructions at once.",
                "**Cache** — fast memory close to the CPU; more cache = fewer slow trips to RAM.",
                "**Instruction set** — all the commands the CPU can run (in machine code).",
              ],
            },
            {
              kind: "callout",
              tone: "mistake",
              title: "Clock speed isn't everything",
              text: "A higher clock speed isn't always faster — cores and cache matter too.",
            },
            {
              kind: "callout",
              tone: "info",
              title: "Embedded systems",
              text: "An **embedded system** is a dedicated computer inside another device (washing machine, car, vending machine) — not a general-purpose PC.",
            },
          ],
        },
      ],
      recall: [
        { id: "s3-l2-r1", prompt: "Name the three stages of the FDE cycle.", answer: "Fetch, decode, execute." },
        { id: "s3-l2-r2", prompt: "Besides clock speed, name two things that affect CPU performance.", answer: "Number of cores and amount of cache." },
      ],
    },
    {
      id: "s3-l3",
      unitId: U,
      topicCode: "3.2",
      title: "Input, output & sensors",
      summary: "Devices that get data in and results out — and choosing sensors.",
      widgets: ["sensor-match"],
      cards: [
        {
          id: "s3-l3-c1",
          title: "Input vs output",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Input", v: "gets data INTO the computer — keyboard, mouse, microphone, scanner, camera, sensor." },
                { k: "Output", v: "presents results — monitor, speaker, printer, projector, actuator." },
              ],
            },
            {
              kind: "p",
              text: "A **sensor** is an input device that measures a physical quantity (temperature, light, moisture, pressure, pH, proximity…). Choose the sensor that matches the quantity you need to measure.",
            },
            { kind: "widget", widget: "sensor-match", caption: "Pick the right sensors for each scenario." },
          ],
        },
      ],
      recall: [
        { id: "s3-l3-r1", prompt: "Is a microphone an input or output device?", answer: "Input — it captures sound into the computer." },
        { id: "s3-l3-r2", prompt: "Which sensor would a system use to water dry soil?", answer: "A moisture sensor." },
      ],
    },
    {
      id: "s3-l4",
      unitId: U,
      topicCode: "3.3",
      title: "Storage: RAM, ROM & secondary",
      summary: "Primary vs secondary storage, types, and virtual memory.",
      widgets: ["ram-rom-sort", "virtual-memory"],
      cards: [
        {
          id: "s3-l4-c1",
          title: "Primary storage: RAM & ROM",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "RAM", v: "volatile, read/write — holds programs & data currently in use. Lost on power off." },
                { k: "ROM", v: "non-volatile, holds boot/firmware. Survives power off." },
              ],
            },
            { kind: "widget", widget: "ram-rom-sort", caption: "Sort each property into RAM or ROM." },
            {
              kind: "callout",
              tone: "mistake",
              title: "Volatile vs non-volatile",
              text: "RAM is **volatile** (forgets when off); ROM is **non-volatile** (remembers). Don't call secondary storage 'memory'.",
            },
          ],
        },
        {
          id: "s3-l4-c2",
          title: "Secondary storage & virtual memory",
          blocks: [
            {
              kind: "p",
              text: "**Secondary** storage is NOT directly accessed by the CPU and stores data permanently:",
            },
            {
              kind: "list",
              items: [
                "**Magnetic** — HDD (spinning platters, tracks, sectors).",
                "**Optical** — CD/DVD/Blu-ray (pits & lands read by a laser).",
                "**Solid-state** — SSD/SD/USB (NAND flash, no moving parts).",
              ],
            },
            { kind: "widget", widget: "virtual-memory", caption: "RAM full → pages move to secondary storage." },
            {
              kind: "callout",
              tone: "info",
              text: "**Virtual memory**: when RAM is full, pages are moved to secondary storage to free space. **Cloud** storage keeps data on remote servers — accessible anywhere, but needs internet and trust in the provider.",
            },
          ],
        },
      ],
      recall: [
        { id: "s3-l4-r1", prompt: "Which is volatile — RAM or ROM?", answer: "RAM (it loses contents without power)." },
        { id: "s3-l4-r2", prompt: "What happens in virtual memory when RAM is full?", answer: "Pages are moved to secondary storage to free up RAM." },
      ],
    },
  ],
  flashcards: [
    { id: "s3-f1", unitId: U, topicCode: "3.1", front: "What does the PC hold?", back: "The address of the next instruction to fetch." },
    { id: "s3-f2", unitId: U, topicCode: "3.1", front: "What does the ACC hold?", back: "The result of ALU calculations." },
    { id: "s3-f3", unitId: U, topicCode: "3.1", front: "CU vs ALU?", back: "CU coordinates/decodes; ALU does arithmetic & logic." },
    { id: "s3-f4", unitId: U, topicCode: "3.1", front: "Three stages of the cycle?", back: "Fetch, decode, execute." },
    { id: "s3-f5", unitId: U, topicCode: "3.1", front: "Three things that affect CPU speed?", back: "Clock speed, number of cores, amount of cache." },
    { id: "s3-f6", unitId: U, topicCode: "3.1", front: "What is an embedded system?", back: "A dedicated computer inside another device (e.g. washing machine)." },
    { id: "s3-f7", unitId: U, topicCode: "3.2", front: "Input vs output device?", back: "Input gets data in (mic, keyboard); output presents results (speaker, printer)." },
    { id: "s3-f8", unitId: U, topicCode: "3.3", front: "RAM vs ROM volatility?", back: "RAM is volatile; ROM is non-volatile." },
    { id: "s3-f9", unitId: U, topicCode: "3.3", front: "Is secondary storage accessed directly by the CPU?", back: "No — only primary storage (RAM/ROM) is." },
    { id: "s3-f10", unitId: U, topicCode: "3.3", front: "Magnetic / optical / solid-state example?", back: "HDD / CD-DVD / SSD." },
    { id: "s3-f11", unitId: U, topicCode: "3.3", front: "What is virtual memory?", back: "Using secondary storage as extra RAM by paging when RAM is full." },
  ],
  drill: [
    {
      id: "s3-d1",
      unitId: U,
      topicCode: "3.1",
      type: "mcq",
      difficulty: "core",
      prompt: "Which register holds the address of the NEXT instruction?",
      explanation: "The Program Counter (PC). The MAR holds the address being accessed right now.",
      choices: [
        { id: "a", text: "PC (Program Counter)" },
        { id: "b", text: "ACC (Accumulator)", misconception: "the ACC holds calculation results, not addresses." },
        { id: "c", text: "MDR (Memory Data Register)", misconception: "the MDR holds fetched data, not the next address." },
      ],
      correctId: "a",
    },
    {
      id: "s3-d2",
      unitId: U,
      topicCode: "3.3",
      type: "truefalse",
      difficulty: "core",
      prompt: "RAM keeps its contents when the computer is switched off.",
      explanation: "No — RAM is volatile. ROM is the non-volatile one.",
      answer: false,
    },
    {
      id: "s3-d3",
      unitId: U,
      topicCode: "3.1",
      type: "truefalse",
      difficulty: "core",
      prompt: "A higher clock speed always makes a CPU faster, regardless of cores and cache.",
      explanation: "No — cores and cache also affect real-world performance.",
      answer: false,
    },
    {
      id: "s3-d4",
      unitId: U,
      topicCode: "3.2",
      type: "mcq",
      difficulty: "core",
      prompt: "Which of these is an OUTPUT device?",
      explanation: "A speaker outputs sound. A microphone and scanner are inputs.",
      choices: [
        { id: "a", text: "Speaker" },
        { id: "b", text: "Microphone", misconception: "a microphone is an input device." },
        { id: "c", text: "Barcode scanner", misconception: "a scanner is an input device." },
      ],
      correctId: "a",
    },
  ],
  masteryTest: {
    passThreshold: 0.8,
    interleaveFromEarlier: 2,
    questions: [
      {
        id: "s3-t1",
        unitId: U,
        topicCode: "3.1",
        type: "mcq",
        difficulty: "core",
        prompt: "Which CPU component performs calculations and logic?",
        explanation: "The ALU (Arithmetic Logic Unit). The CU coordinates and decodes.",
        choices: [
          { id: "a", text: "ALU" },
          { id: "b", text: "CU", misconception: "the CU decodes/coordinates; the ALU does the maths." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t2",
        unitId: U,
        topicCode: "3.1",
        type: "mcq",
        difficulty: "core",
        prompt: "Which register holds the result of an ALU calculation?",
        explanation: "The Accumulator (ACC).",
        choices: [
          { id: "a", text: "ACC" },
          { id: "b", text: "PC", misconception: "the PC holds the next instruction's address, not results." },
          { id: "c", text: "MAR", misconception: "the MAR holds the address being accessed, not results." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t3",
        unitId: U,
        topicCode: "3.1",
        type: "order",
        difficulty: "core",
        prompt: "Put the cycle stages in order.",
        explanation: "Fetch → Decode → Execute, repeated.",
        items: [
          { id: "decode", text: "Decode" },
          { id: "execute", text: "Execute" },
          { id: "fetch", text: "Fetch" },
        ],
        correctOrder: ["fetch", "decode", "execute"],
      },
      {
        id: "s3-t4",
        unitId: U,
        topicCode: "3.1",
        type: "truefalse",
        difficulty: "stretch",
        prompt: "Doubling the clock speed always doubles real-world performance.",
        explanation: "No — cores and cache also matter; bottlenecks elsewhere limit gains.",
        answer: false,
      },
      {
        id: "s3-t5",
        unitId: U,
        topicCode: "3.1",
        type: "mcq",
        difficulty: "core",
        commandWord: "Identify",
        prompt: "Which is an embedded system?",
        explanation: "An embedded system is a dedicated computer inside a device, like a washing machine.",
        choices: [
          { id: "a", text: "The controller inside a washing machine" },
          { id: "b", text: "A general-purpose laptop", misconception: "a laptop is general-purpose, not embedded." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t6",
        unitId: U,
        topicCode: "3.1",
        type: "mcq",
        difficulty: "core",
        prompt: "The instruction set of a CPU is…",
        explanation: "All the commands (in machine code) a CPU can execute.",
        choices: [
          { id: "a", text: "all the commands the CPU can carry out" },
          { id: "b", text: "the list of programs installed", misconception: "installed programs aren't the CPU's instruction set." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t7",
        unitId: U,
        topicCode: "3.2",
        type: "mcq",
        difficulty: "core",
        prompt: "Which is an INPUT device?",
        explanation: "A microphone captures sound into the computer (input).",
        choices: [
          { id: "a", text: "Microphone" },
          { id: "b", text: "Speaker", misconception: "a speaker outputs sound — it's an output device." },
          { id: "c", text: "Laser printer", misconception: "a printer is an output device." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t8",
        unitId: U,
        topicCode: "3.2",
        type: "mcq",
        difficulty: "core",
        commandWord: "Suggest",
        prompt: "A system must keep greenhouse soil watered. Which sensor fits best?",
        explanation: "A moisture sensor detects how wet the soil is.",
        choices: [
          { id: "a", text: "Moisture sensor" },
          { id: "b", text: "Light sensor", misconception: "light tells you brightness, not soil wetness." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t9",
        unitId: U,
        topicCode: "3.3",
        type: "truefalse",
        difficulty: "core",
        prompt: "RAM is volatile — it loses its contents when the power is off.",
        explanation: "Correct. ROM is the non-volatile one.",
        answer: true,
      },
      {
        id: "s3-t10",
        unitId: U,
        topicCode: "3.3",
        type: "mcq",
        difficulty: "core",
        prompt: "What does ROM typically store?",
        explanation: "ROM holds the boot-up/firmware instructions and is non-volatile.",
        choices: [
          { id: "a", text: "The start-up (boot) instructions" },
          { id: "b", text: "The programs currently running", misconception: "running programs live in RAM, not ROM." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t11",
        unitId: U,
        topicCode: "3.3",
        type: "truefalse",
        difficulty: "core",
        prompt: "Secondary storage is accessed directly by the CPU.",
        explanation: "No — only primary storage (RAM/ROM) is directly accessed by the CPU.",
        answer: false,
      },
      {
        id: "s3-t12",
        unitId: U,
        topicCode: "3.3",
        type: "mcq",
        difficulty: "core",
        commandWord: "Identify",
        prompt: "Which is a MAGNETIC storage device?",
        explanation: "An HDD stores data magnetically on spinning platters.",
        choices: [
          { id: "a", text: "Hard disk drive (HDD)" },
          { id: "b", text: "SSD", misconception: "an SSD is solid-state (flash), not magnetic." },
          { id: "c", text: "DVD", misconception: "a DVD is optical, not magnetic." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t13",
        unitId: U,
        topicCode: "3.3",
        type: "mcq",
        difficulty: "stretch",
        prompt: "When RAM is full, virtual memory…",
        explanation: "Pages are moved to secondary storage to free up RAM.",
        choices: [
          { id: "a", text: "moves pages to secondary storage to free up RAM" },
          { id: "b", text: "adds more ROM", misconception: "ROM isn't used as working memory; virtual memory uses secondary storage." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t14",
        unitId: U,
        topicCode: "3.1",
        type: "mcq",
        difficulty: "core",
        prompt: "Which bus carries the location (address) being read or written?",
        explanation: "The address bus carries addresses; the data bus carries the data.",
        choices: [
          { id: "a", text: "Address bus" },
          { id: "b", text: "Data bus", misconception: "the data bus carries the data itself, not the address." },
        ],
        correctId: "a",
      },
      {
        id: "s3-t15",
        unitId: U,
        topicCode: "3.1",
        type: "mcq",
        difficulty: "core",
        prompt: "During FETCH, the address in the PC is first copied to the…",
        explanation: "PC → MAR, so the correct memory location can be read.",
        choices: [
          { id: "a", text: "MAR" },
          { id: "b", text: "ACC", misconception: "the ACC holds results, not the address to fetch." },
        ],
        correctId: "a",
      },
    ],
  },
  tutor: {
    conceptSummary:
      "Sector 3 covers hardware: the CPU/microprocessor and the Von Neumann model (CU, ALU; registers PC=next-instruction-address, MAR=current address, MDR=fetched data, CIR=current instruction, ACC=ALU result; address/data/control buses); the fetch–decode–execute cycle; performance (clock speed, cores, cache, instruction set); embedded systems; input vs output devices and sensors (choose the sensor matching the quantity); and storage — primary RAM (volatile) vs ROM (non-volatile), secondary magnetic/optical/solid-state (not directly accessed by the CPU), virtual memory (paging when RAM is full) and cloud.",
    misconceptions: [
      "Confusing RAM (volatile) with ROM (non-volatile) — which survives power off.",
      "Calling secondary storage 'memory'; only RAM/ROM are directly accessed by the CPU.",
      "Swapping the ACC and PC roles (ACC = results, PC = next instruction address).",
      "Assuming more clock speed always means faster, ignoring cores and cache.",
    ],
  },
};
