import type { Unit } from "./types";

/** Sector 2 — Data Transmission (syllabus 2.1–2.3). First sector with interleaving. */
const U = "sector-2";

export const dataTransmission: Unit = {
  id: U,
  order: 2,
  syllabusRef: "2.1–2.3",
  paper: 1,
  title: "Data Transmission",
  blurb: "Packets, serial/parallel, duplex, error detection & encryption.",
  sector: { number: 2, name: "Data Transmission", boss: "Packetstorm" },
  isRewardSector: true,
  lessons: [
    {
      id: "s2-l1",
      unitId: U,
      topicCode: "2.1",
      title: "Packets & packet switching",
      summary: "How data is chopped up, routed, and reassembled.",
      widgets: ["packet-switch"],
      cards: [
        {
          id: "s2-l1-c1",
          title: "What's in a packet",
          blocks: [
            { kind: "p", text: "Data is split into **packets**. Each packet has three parts:" },
            {
              kind: "kv",
              rows: [
                { k: "Header", v: "destination address, packet number, originator's (sender's) address." },
                { k: "Payload", v: "the actual data being carried." },
                { k: "Trailer", v: "marks the end of the packet and helps check for errors." },
              ],
            },
          ],
        },
        {
          id: "s2-l1-c2",
          title: "Packet switching",
          blocks: [
            {
              kind: "p",
              text: "In **packet switching**, each packet can take a **different route** — a **router** chooses the best path. Packets can arrive **out of order** and are **reordered after the last one arrives**, using the packet number in the header.",
            },
            { kind: "widget", widget: "packet-switch", caption: "Transmit, watch them scatter and arrive out of order, then reassemble." },
          ],
        },
      ],
      recall: [
        { id: "s2-l1-r1", prompt: "Name the three parts of a packet.", answer: "Header, payload, trailer." },
        { id: "s2-l1-r2", prompt: "How does the receiver put out-of-order packets back together?", answer: "Using the packet number in each header, after the last one arrives." },
      ],
    },
    {
      id: "s2-l2",
      unitId: U,
      topicCode: "2.1",
      title: "Serial, parallel & duplex",
      summary: "Directions and wires — and why parallel isn't always 'better'.",
      widgets: [],
      cards: [
        {
          id: "s2-l2-c1",
          title: "Serial vs parallel",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Serial", v: "one bit at a time, down a single wire. Reliable over long distances." },
                { k: "Parallel", v: "multiple bits at once, over multiple wires. Faster over short distances." },
              ],
            },
            {
              kind: "callout",
              tone: "mistake",
              title: "Parallel isn't always better",
              text: "Over distance, parallel wires suffer **skew** (bits arrive at slightly different times) — so serial is used for long links like USB.",
            },
          ],
        },
        {
          id: "s2-l2-c2",
          title: "Simplex, half- and full-duplex",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Simplex", v: "one direction only (e.g. TV broadcast)." },
                { k: "Half-duplex", v: "both directions, but one at a time (e.g. walkie-talkie)." },
                { k: "Full-duplex", v: "both directions at the same time (e.g. phone call)." },
              ],
            },
            { kind: "callout", tone: "info", text: "**USB** uses serial transmission; it's widely compatible, can power devices, but has a limited cable length." },
          ],
        },
      ],
      recall: [
        { id: "s2-l2-r1", prompt: "Why is serial preferred over parallel for long distances?", answer: "Parallel suffers skew — bits arrive out of sync — so serial is more reliable." },
        { id: "s2-l2-r2", prompt: "Difference between half- and full-duplex?", answer: "Half = both ways but one at a time; full = both ways simultaneously." },
      ],
    },
    {
      id: "s2-l3",
      unitId: U,
      topicCode: "2.2",
      title: "Error detection",
      summary: "Catching the errors interference causes — parity, checksum, check digits, ARQ.",
      widgets: ["parity-calc", "check-digit"],
      cards: [
        {
          id: "s2-l3-c1",
          title: "Why errors happen — and parity",
          blocks: [
            {
              kind: "p",
              text: "**Interference** can corrupt bits during transmission. A **parity check** adds one bit so the number of 1s is always **even** (even parity) or **odd** (odd parity). If a single bit flips, the count breaks and the error is detected.",
            },
            { kind: "widget", widget: "parity-calc", caption: "Flip a bit — the parity check fails." },
          ],
        },
        {
          id: "s2-l3-c2",
          title: "Other methods",
          blocks: [
            {
              kind: "list",
              items: [
                "**Checksum** — a value calculated from the data, sent alongside it; recalculated and compared at the other end.",
                "**Echo check** — the receiver sends the data back to compare with the original.",
                "**Check digit** — an extra digit on the end (ISBNs, barcodes) that catches entry errors.",
                "**ARQ** (Automatic Repeat reQuest) — uses acknowledgements + a timeout to **request a resend**.",
              ],
            },
            { kind: "widget", widget: "check-digit", caption: "A real ISBN — change a digit and it's caught." },
            {
              kind: "callout",
              tone: "mistake",
              title: "Detect, not correct",
              text: "Most methods only **detect** errors. To fix them, ARQ asks the sender to **resend** — the method itself doesn't repair the data.",
            },
          ],
        },
      ],
      recall: [
        { id: "s2-l3-r1", prompt: "An even-parity byte has how many 1s?", answer: "An even number of 1s." },
        { id: "s2-l3-r2", prompt: "Do error-detection methods usually correct errors?", answer: "No — they detect. ARQ then requests a resend." },
      ],
    },
    {
      id: "s2-l4",
      unitId: U,
      topicCode: "2.3",
      title: "Encryption",
      summary: "Protecting data in transit — symmetric vs asymmetric keys.",
      widgets: ["encryption-keys"],
      cards: [
        {
          id: "s2-l4-c1",
          title: "Symmetric & asymmetric",
          blocks: [
            { kind: "p", text: "**Encryption** scrambles data so it's meaningless if intercepted. Two approaches:" },
            {
              kind: "kv",
              rows: [
                { k: "Symmetric", v: "the SAME key encrypts and decrypts — both sides must share it secretly." },
                { k: "Asymmetric", v: "a PUBLIC key encrypts; only the matching PRIVATE key can decrypt." },
              ],
            },
            { kind: "widget", widget: "encryption-keys", caption: "Switch modes and see which key does what." },
            {
              kind: "callout",
              tone: "mistake",
              title: "Which key?",
              text: "In asymmetric encryption the **public** key encrypts and the **private** key decrypts. The private key is never shared.",
            },
          ],
        },
      ],
      recall: [
        { id: "s2-l4-r1", prompt: "In symmetric encryption, how many keys and who has them?", answer: "One shared key, held secretly by both sides." },
        { id: "s2-l4-r2", prompt: "In asymmetric encryption, which key decrypts?", answer: "The private key." },
      ],
    },
  ],
  flashcards: [
    { id: "s2-f1", unitId: U, topicCode: "2.1", front: "Three parts of a packet?", back: "Header, payload, trailer." },
    { id: "s2-f2", unitId: U, topicCode: "2.1", front: "What's in a packet header?", back: "Destination address, packet number, originator's address." },
    { id: "s2-f3", unitId: U, topicCode: "2.1", front: "Serial vs parallel?", back: "Serial: one bit at a time, one wire. Parallel: many bits at once, many wires." },
    { id: "s2-f4", unitId: U, topicCode: "2.1", front: "Why serial over distance?", back: "Parallel suffers skew; serial stays in sync." },
    { id: "s2-f5", unitId: U, topicCode: "2.1", front: "Simplex / half-duplex / full-duplex?", back: "One way / both ways one-at-a-time / both ways at once." },
    { id: "s2-f6", unitId: U, topicCode: "2.2", front: "Even parity means…?", back: "The total number of 1s is even." },
    { id: "s2-f7", unitId: U, topicCode: "2.2", front: "What does ARQ do?", back: "Uses acknowledgements + timeout to request a resend." },
    { id: "s2-f8", unitId: U, topicCode: "2.2", front: "Where are check digits used?", back: "ISBNs and barcodes." },
    { id: "s2-f9", unitId: U, topicCode: "2.3", front: "Symmetric encryption key?", back: "One shared key for both encrypt and decrypt." },
    { id: "s2-f10", unitId: U, topicCode: "2.3", front: "Asymmetric: which key decrypts?", back: "The private key (public key encrypts)." },
  ],
  drill: [
    {
      id: "s2-d1",
      unitId: U,
      topicCode: "2.1",
      type: "truefalse",
      difficulty: "core",
      prompt: "Parallel transmission is always better than serial.",
      explanation: "No — over distance, parallel suffers skew, so serial is preferred (e.g. USB).",
      answer: false,
    },
    {
      id: "s2-d2",
      unitId: U,
      topicCode: "2.1",
      type: "mcq",
      difficulty: "core",
      prompt: "A walkie-talkie (talk, then listen) is an example of…",
      explanation: "Both directions but one at a time = half-duplex.",
      choices: [
        { id: "a", text: "half-duplex" },
        { id: "b", text: "full-duplex", misconception: "full-duplex is both directions at once, like a phone call." },
        { id: "c", text: "simplex", misconception: "simplex is one direction only." },
      ],
      correctId: "a",
    },
    {
      id: "s2-d3",
      unitId: U,
      topicCode: "2.2",
      type: "truefalse",
      difficulty: "core",
      prompt: "A parity check can correct the bit that went wrong.",
      explanation: "A simple parity check only detects an error, it can't locate or correct it.",
      answer: false,
    },
    {
      id: "s2-d4",
      unitId: U,
      topicCode: "2.3",
      type: "mcq",
      difficulty: "core",
      prompt: "In asymmetric encryption, the public key is used to…",
      explanation: "The public key encrypts; the private key decrypts.",
      choices: [
        { id: "a", text: "encrypt the message" },
        { id: "b", text: "decrypt the message", misconception: "decryption uses the private key, not the public key." },
      ],
      correctId: "a",
    },
  ],
  masteryTest: {
    passThreshold: 0.8,
    interleaveFromEarlier: 2,
    questions: [
      {
        id: "s2-t1",
        unitId: U,
        topicCode: "2.1",
        type: "mcq",
        difficulty: "core",
        commandWord: "Identify",
        prompt: "Which is found in a packet's HEADER?",
        explanation: "The header holds addressing info: destination address, packet number, originator's address.",
        choices: [
          { id: "a", text: "The destination address" },
          { id: "b", text: "The actual file data", misconception: "the data is the payload, not the header." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t2",
        unitId: U,
        topicCode: "2.1",
        type: "mcq",
        difficulty: "core",
        prompt: "In packet switching, packets…",
        explanation: "Each packet can take a different route and arrive out of order; the receiver reorders them.",
        choices: [
          { id: "a", text: "may take different routes and arrive out of order" },
          { id: "b", text: "always follow the same route in order", misconception: "that's more like circuit switching — packet switching routes each packet independently." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t3",
        unitId: U,
        topicCode: "2.1",
        type: "truefalse",
        difficulty: "core",
        prompt: "Out-of-order packets are reassembled using the packet number in the header.",
        explanation: "Correct — that's exactly what the packet number is for.",
        answer: true,
      },
      {
        id: "s2-t4",
        unitId: U,
        topicCode: "2.1",
        type: "mcq",
        difficulty: "core",
        prompt: "Serial transmission sends…",
        explanation: "Serial = one bit at a time down a single wire.",
        choices: [
          { id: "a", text: "one bit at a time down one wire" },
          { id: "b", text: "many bits at once down many wires", misconception: "that's parallel transmission." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t5",
        unitId: U,
        topicCode: "2.1",
        type: "truefalse",
        difficulty: "stretch",
        prompt: "Parallel transmission is always the better choice.",
        explanation: "No — over distance, skew makes parallel unreliable, so serial is used.",
        answer: false,
      },
      {
        id: "s2-t6",
        unitId: U,
        topicCode: "2.1",
        type: "mcq",
        difficulty: "core",
        prompt: "A phone call (both people talk at once) is…",
        explanation: "Both directions simultaneously = full-duplex.",
        choices: [
          { id: "a", text: "full-duplex" },
          { id: "b", text: "half-duplex", misconception: "half-duplex is one direction at a time, like a walkie-talkie." },
          { id: "c", text: "simplex", misconception: "simplex is one-way only." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t7",
        unitId: U,
        topicCode: "2.2",
        type: "mcq",
        difficulty: "core",
        prompt: "An even-parity system adds a parity bit so that…",
        explanation: "Even parity keeps the total number of 1s even.",
        choices: [
          { id: "a", text: "the total number of 1s is even" },
          { id: "b", text: "the total number of 1s is odd", misconception: "that's odd parity." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t8",
        unitId: U,
        topicCode: "2.2",
        type: "truefalse",
        difficulty: "core",
        prompt: "Most error-detection methods correct the error they find.",
        explanation: "They mostly only detect. ARQ then requests a resend to fix it.",
        answer: false,
      },
      {
        id: "s2-t9",
        unitId: U,
        topicCode: "2.2",
        type: "mcq",
        difficulty: "core",
        commandWord: "Identify",
        prompt: "Which method sends a calculated value with the data and recalculates it at the other end?",
        explanation: "That's a checksum.",
        choices: [
          { id: "a", text: "Checksum" },
          { id: "b", text: "Echo check", misconception: "an echo check sends the data back, it doesn't calculate a value." },
          { id: "c", text: "Parity bit", misconception: "a parity bit is a single bit, not a calculated value over the data." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t10",
        unitId: U,
        topicCode: "2.2",
        type: "mcq",
        difficulty: "core",
        prompt: "ARQ detects a problem and then…",
        explanation: "ARQ uses acknowledgements and a timeout to request the data be re-sent.",
        choices: [
          { id: "a", text: "requests the data to be re-sent" },
          { id: "b", text: "repairs the corrupted bits itself", misconception: "ARQ doesn't repair data; it asks for a resend." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t11",
        unitId: U,
        topicCode: "2.2",
        type: "mcq",
        difficulty: "core",
        prompt: "Check digits are commonly used in…",
        explanation: "ISBNs and barcodes use a check digit to catch entry errors.",
        choices: [
          { id: "a", text: "ISBNs and barcodes" },
          { id: "b", text: "encrypting passwords", misconception: "that's encryption/hashing, not a check digit." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t12",
        unitId: U,
        topicCode: "2.3",
        type: "mcq",
        difficulty: "core",
        prompt: "Symmetric encryption uses…",
        explanation: "The same secret key encrypts and decrypts.",
        choices: [
          { id: "a", text: "the same key to encrypt and decrypt" },
          { id: "b", text: "a public key and a private key", misconception: "that's asymmetric encryption." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t13",
        unitId: U,
        topicCode: "2.3",
        type: "mcq",
        difficulty: "stretch",
        prompt: "In asymmetric encryption, which key can decrypt the message?",
        explanation: "Only the private key decrypts; the public key encrypts.",
        choices: [
          { id: "a", text: "The private key" },
          { id: "b", text: "The public key", misconception: "the public key encrypts — only the private key decrypts." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t14",
        unitId: U,
        topicCode: "2.3",
        type: "mcq",
        difficulty: "core",
        commandWord: "State",
        prompt: "The main purpose of encryption is to…",
        explanation: "Encryption makes intercepted data meaningless without the key.",
        choices: [
          { id: "a", text: "make data meaningless if it's intercepted" },
          { id: "b", text: "make the file smaller", misconception: "that's compression, not encryption." },
        ],
        correctId: "a",
      },
      {
        id: "s2-t15",
        unitId: U,
        topicCode: "2.1",
        type: "order",
        difficulty: "core",
        prompt: "Order a packet's parts from first sent to last.",
        explanation: "A packet is sent header → payload → trailer.",
        items: [
          { id: "payload", text: "Payload" },
          { id: "header", text: "Header" },
          { id: "trailer", text: "Trailer" },
        ],
        correctOrder: ["header", "payload", "trailer"],
      },
    ],
  },
  tutor: {
    conceptSummary:
      "Sector 2 covers data transmission: packets (header with destination address/packet number/originator address, payload, trailer) and packet switching (different routes, router chooses, out-of-order arrival reordered after the last packet); serial (one bit/one wire) vs parallel (many bits/many wires, skew over distance), and simplex/half-duplex/full-duplex; USB; error detection (parity odd/even + parity byte, checksum, echo check, check digit in ISBN/barcodes, ARQ with acknowledgements + timeout — methods mostly DETECT not correct); and encryption (symmetric = same shared key; asymmetric = public key encrypts, private key decrypts).",
    misconceptions: [
      "Thinking error-detection methods correct errors — they mostly only detect (ARQ requests a resend).",
      "Confusing which key is public vs private in asymmetric encryption (public encrypts, private decrypts).",
      "Thinking parallel is always better than serial — it suffers skew over distance.",
      "Mixing up half-duplex (one direction at a time) and full-duplex (both at once).",
    ],
  },
};
