import type { Unit } from "./types";

/** Sector 5 — Algorithm Design & Problem-Solving (syllabus 7; Paper 2). The biggest gap, weighted heaviest. */
const U = "sector-5";

export const algorithms: Unit = {
  id: U,
  order: 5,
  syllabusRef: "7",
  paper: 2,
  title: "Algorithms & Problem-Solving",
  blurb: "Life cycle, flowcharts, pseudocode, standard algorithms, testing & traces.",
  sector: { number: 5, name: "Algorithms & Problem-Solving", boss: "The Null Pointer" },
  isRewardSector: true,
  lessons: [
    {
      id: "s5-l1",
      unitId: U,
      topicCode: "7.1",
      title: "The development life cycle",
      summary: "Analysis → design → coding → testing, plus abstraction & decomposition.",
      widgets: [],
      cards: [
        {
          id: "s5-l1-c1",
          title: "Four stages",
          blocks: [
            {
              kind: "list",
              ordered: true,
              items: [
                "**Analysis** — understand the problem; use **abstraction** and **decomposition**.",
                "**Design** — plan it with structure diagrams, flowcharts and pseudocode.",
                "**Coding** — write and iteratively test the program.",
                "**Testing** — run it with carefully chosen test data.",
              ],
            },
            {
              kind: "kv",
              rows: [
                { k: "Abstraction", v: "remove unnecessary detail to focus on what matters." },
                { k: "Decomposition", v: "break a problem into smaller sub-problems (inputs, processes, outputs, storage)." },
              ],
            },
          ],
        },
      ],
      recall: [
        { id: "s5-l1-r1", prompt: "Name the four stages of the development life cycle.", answer: "Analysis, design, coding, testing." },
        { id: "s5-l1-r2", prompt: "What is decomposition?", answer: "Breaking a problem into smaller, more manageable sub-problems." },
      ],
    },
    {
      id: "s5-l2",
      unitId: U,
      topicCode: "7.2",
      title: "Flowcharts",
      summary: "The official symbols — and running one with sample input.",
      widgets: ["flowchart-builder"],
      cards: [
        {
          id: "s5-l2-c1",
          title: "The symbols",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Terminator", v: "rounded box — Start / Stop." },
                { k: "Process", v: "rectangle — a calculation or assignment." },
                { k: "Input/Output", v: "parallelogram — INPUT or OUTPUT." },
                { k: "Decision", v: "diamond — a yes/no question with two branches." },
                { k: "Flow line", v: "arrow — shows the order of steps." },
              ],
            },
            { kind: "widget", widget: "flowchart-builder", caption: "Run the flowchart and watch the path light up." },
          ],
        },
      ],
      recall: [
        { id: "s5-l2-r1", prompt: "Which flowchart symbol has two exits?", answer: "The decision (diamond)." },
        { id: "s5-l2-r2", prompt: "What shape is used for INPUT and OUTPUT?", answer: "A parallelogram." },
      ],
    },
    {
      id: "s5-l3",
      unitId: U,
      topicCode: "7.3",
      title: "Pseudocode",
      summary: "Cambridge conventions — and a step-runner that executes them.",
      widgets: ["pseudocode-runner"],
      cards: [
        {
          id: "s5-l3-c1",
          title: "Cambridge conventions",
          blocks: [
            {
              kind: "list",
              items: [
                "Keywords in **UPPER CASE**; `←` for assignment; `DECLARE Id : TYPE`.",
                "Selection: `IF…THEN…ELSE…ENDIF`, `CASE OF…OTHERWISE…ENDCASE`.",
                "Iteration: `FOR…NEXT` (count), `WHILE…DO…ENDWHILE` (check first), `REPEAT…UNTIL` (check last).",
                "Operators `+ - * / ^`, `MOD`, `DIV`, relational `= <> < <= > >=`, logical `AND OR NOT`.",
              ],
            },
            {
              kind: "code",
              lang: "pseudocode",
              caption: "A totalling loop in Cambridge style.",
              lines: [
                "DECLARE Total : INTEGER",
                "Total ← 0",
                "FOR Count ← 1 TO 10",
                "   Total ← Total + Count",
                "NEXT Count",
                'OUTPUT "Total is ", Total',
              ],
            },
            { kind: "widget", widget: "pseudocode-runner", caption: "Step through real pseudocode and watch the variables." },
          ],
        },
      ],
      recall: [
        { id: "s5-l3-r1", prompt: "Which symbol does Cambridge pseudocode use for assignment?", answer: "← (a left arrow)." },
        { id: "s5-l3-r2", prompt: "Difference between WHILE and REPEAT loops?", answer: "WHILE checks the condition first (may run 0 times); REPEAT checks at the end (runs at least once)." },
      ],
    },
    {
      id: "s5-l4",
      unitId: U,
      topicCode: "7.4",
      title: "Standard algorithms",
      summary: "Linear search, bubble sort, totalling, counting, max/min/average.",
      widgets: ["sort-search-visualiser"],
      cards: [
        {
          id: "s5-l4-c1",
          title: "The classics",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Linear search", v: "check each item in turn until you find it (or run out)." },
                { k: "Bubble sort", v: "compare ADJACENT items and swap if out of order; repeat passes." },
                { k: "Totalling / counting", v: "running total / counting how many meet a condition." },
                { k: "Max / min / average", v: "track the biggest/smallest; sum ÷ count for the average." },
              ],
            },
            { kind: "widget", widget: "sort-search-visualiser", caption: "Step through every comparison and swap." },
          ],
        },
      ],
      recall: [
        { id: "s5-l4-r1", prompt: "What does bubble sort compare on each step?", answer: "Two adjacent items, swapping them if they're in the wrong order." },
        { id: "s5-l4-r2", prompt: "How do you compute an average in an algorithm?", answer: "Keep a running total and a count, then divide total by count." },
      ],
    },
    {
      id: "s5-l5",
      unitId: U,
      topicCode: "7.5",
      title: "Validation vs verification",
      summary: "The single most-confused pair in the exam.",
      widgets: ["classify-drill"],
      cards: [
        {
          id: "s5-l5-c1",
          title: "Two different jobs",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Validation", v: "the PROGRAM checks input is sensible: range, length, type, presence, format, check digit." },
                { k: "Verification", v: "checking data was entered/copied ACCURATELY: visual check, double-entry check." },
              ],
            },
            { kind: "widget", widget: "classify-drill", caption: "Drill it until it's automatic." },
            {
              kind: "callout",
              tone: "mistake",
              title: "Validation ≠ correct",
              text: "Validation only checks data is **sensible** (e.g. in range). It can't tell if it's the **right** value — that needs verification.",
            },
          ],
        },
      ],
      recall: [
        { id: "s5-l5-r1", prompt: "Is a double-entry check validation or verification?", answer: "Verification — it checks accurate entry." },
        { id: "s5-l5-r2", prompt: "Name three types of validation.", answer: "Any of: range, length, type, presence, format, check digit." },
      ],
    },
    {
      id: "s5-l6",
      unitId: U,
      topicCode: "7.6",
      title: "Test data & trace tables",
      summary: "Normal / abnormal / extreme / boundary — and dry-running code.",
      widgets: ["classify-drill", "trace-table"],
      cards: [
        {
          id: "s5-l6-c1",
          title: "Choosing test data",
          blocks: [
            {
              kind: "kv",
              rows: [
                { k: "Normal", v: "typical, accepted data." },
                { k: "Abnormal", v: "data that should be rejected." },
                { k: "Extreme", v: "the largest / smallest ACCEPTED value." },
                { k: "Boundary", v: "the largest/smallest accepted value AND the value just outside it." },
              ],
            },
            {
              kind: "callout",
              tone: "mistake",
              title: "Extreme vs boundary",
              text: "**Extreme** is one accepted edge value. **Boundary** tests that edge value **and** its rejected neighbour together.",
            },
          ],
        },
        {
          id: "s5-l6-c2",
          title: "Trace tables",
          blocks: [
            { kind: "p", text: "A **trace table** dry-runs an algorithm: track each variable (and any output) as you step through it." },
            { kind: "widget", widget: "trace-table", caption: "Fill the trace, then check it." },
          ],
        },
      ],
      recall: [
        { id: "s5-l6-r1", prompt: "For a 1–100 field, what is an extreme value?", answer: "1 or 100 — the smallest/largest accepted value." },
        { id: "s5-l6-r2", prompt: "What does a trace table track?", answer: "The value of each variable (and outputs) at each step of the algorithm." },
      ],
    },
  ],
  flashcards: [
    { id: "s5-f1", unitId: U, topicCode: "7.1", front: "Four stages of the life cycle?", back: "Analysis, design, coding, testing." },
    { id: "s5-f2", unitId: U, topicCode: "7.1", front: "Abstraction means…?", back: "Removing unnecessary detail to focus on what matters." },
    { id: "s5-f3", unitId: U, topicCode: "7.1", front: "Decomposition means…?", back: "Breaking a problem into smaller sub-problems." },
    { id: "s5-f4", unitId: U, topicCode: "7.2", front: "Which flowchart symbol is a diamond?", back: "Decision — a yes/no question with two branches." },
    { id: "s5-f5", unitId: U, topicCode: "7.3", front: "Pseudocode assignment symbol?", back: "← (left arrow)." },
    { id: "s5-f6", unitId: U, topicCode: "7.3", front: "WHILE vs REPEAT?", back: "WHILE checks first (0+ times); REPEAT checks last (1+ times)." },
    { id: "s5-f7", unitId: U, topicCode: "7.4", front: "Bubble sort compares…?", back: "Adjacent items, swapping if out of order." },
    { id: "s5-f8", unitId: U, topicCode: "7.4", front: "Linear search does…?", back: "Checks each item in turn until found or the end." },
    { id: "s5-f9", unitId: U, topicCode: "7.5", front: "Validation vs verification?", back: "Validation = input is sensible; verification = entered/copied accurately." },
    { id: "s5-f10", unitId: U, topicCode: "7.5", front: "Two verification methods?", back: "Visual check and double-entry check." },
    { id: "s5-f11", unitId: U, topicCode: "7.6", front: "Extreme vs boundary test data?", back: "Extreme = one accepted edge value; boundary = that edge AND its rejected neighbour." },
    { id: "s5-f12", unitId: U, topicCode: "7.6", front: "Abnormal test data is…?", back: "Data that should be rejected." },
  ],
  drill: [
    {
      id: "s5-d1",
      unitId: U,
      topicCode: "7.5",
      type: "mcq",
      difficulty: "core",
      prompt: "Typing a password twice to confirm it matches is…",
      explanation: "A double-entry check confirms accurate entry — that's verification.",
      choices: [
        { id: "a", text: "verification" },
        { id: "b", text: "validation", misconception: "validation checks data is sensible; matching two entries is verification." },
      ],
      correctId: "a",
    },
    {
      id: "s5-d2",
      unitId: U,
      topicCode: "7.6",
      type: "mcq",
      difficulty: "core",
      prompt: "For a field accepting 1–100, the value 100 is…",
      explanation: "100 is the largest accepted value — extreme test data.",
      choices: [
        { id: "a", text: "extreme" },
        { id: "b", text: "abnormal", misconception: "100 is accepted, so it's not abnormal." },
        { id: "c", text: "normal", misconception: "100 is the edge value, more specific than 'normal'." },
      ],
      correctId: "a",
    },
    {
      id: "s5-d3",
      unitId: U,
      topicCode: "7.4",
      type: "numeric",
      difficulty: "core",
      prompt: "Total ← 0; FOR i ← 1 TO 4: Total ← Total + i. What is the final Total?",
      explanation: "1+2+3+4 = 10.",
      answer: 10,
    },
    {
      id: "s5-d4",
      unitId: U,
      topicCode: "7.3",
      type: "mcq",
      difficulty: "core",
      prompt: "Which loop always runs its body at least once?",
      explanation: "REPEAT…UNTIL checks the condition at the end, so it runs at least once.",
      choices: [
        { id: "a", text: "REPEAT…UNTIL" },
        { id: "b", text: "WHILE…ENDWHILE", misconception: "WHILE checks first, so it can run zero times." },
      ],
      correctId: "a",
    },
  ],
  masteryTest: {
    passThreshold: 0.8,
    interleaveFromEarlier: 3,
    questions: [
      {
        id: "s5-t1",
        unitId: U,
        topicCode: "7.5",
        type: "mcq",
        difficulty: "core",
        commandWord: "Identify",
        prompt: "A program checks an entered age is between 0 and 120. This is…",
        explanation: "Checking input is sensible (a range check) is validation.",
        choices: [
          { id: "a", text: "validation (range check)" },
          { id: "b", text: "verification", misconception: "verification checks accurate entry, not whether a value is sensible." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t2",
        unitId: U,
        topicCode: "7.5",
        type: "mcq",
        difficulty: "core",
        prompt: "Proofreading typed data against the original document is…",
        explanation: "A visual check is verification.",
        choices: [
          { id: "a", text: "verification (visual check)" },
          { id: "b", text: "validation", misconception: "this checks accurate copying — verification, not validation." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t3",
        unitId: U,
        topicCode: "7.5",
        type: "truefalse",
        difficulty: "stretch",
        prompt: "If data passes validation, it must be correct.",
        explanation: "No — validation only checks data is sensible, not that it's the right value.",
        answer: false,
      },
      {
        id: "s5-t4",
        unitId: U,
        topicCode: "7.5",
        type: "mcq",
        difficulty: "core",
        prompt: "Checking a field is not left blank is which type of validation?",
        explanation: "A presence check ensures something was entered.",
        choices: [
          { id: "a", text: "presence check" },
          { id: "b", text: "double-entry check", misconception: "double-entry is verification, not validation." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t5",
        unitId: U,
        topicCode: "7.6",
        type: "mcq",
        difficulty: "core",
        prompt: "For a field accepting 0–100, what is a NORMAL test value?",
        explanation: "A typical accepted value like 50.",
        choices: [
          { id: "a", text: "50" },
          { id: "b", text: "100", misconception: "100 is the extreme (edge) value, not a normal one." },
          { id: "c", text: "150", misconception: "150 is abnormal — it should be rejected." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t6",
        unitId: U,
        topicCode: "7.6",
        type: "mcq",
        difficulty: "stretch",
        prompt: "Which best describes BOUNDARY test data for a 1–100 field?",
        explanation: "Boundary tests the edge value AND its rejected neighbour (e.g. 100 and 101).",
        choices: [
          { id: "a", text: "100 and 101 tested together" },
          { id: "b", text: "just 100", misconception: "that's extreme — boundary also tests the rejected neighbour." },
          { id: "c", text: "50", misconception: "that's a normal value, not a boundary." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t7",
        unitId: U,
        topicCode: "7.6",
        type: "mcq",
        difficulty: "core",
        prompt: "A value the program SHOULD reject is called…",
        explanation: "Abnormal test data should be rejected.",
        choices: [
          { id: "a", text: "abnormal" },
          { id: "b", text: "extreme", misconception: "extreme values are accepted edge values, not rejected ones." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t8",
        unitId: U,
        topicCode: "7.1",
        type: "order",
        difficulty: "core",
        prompt: "Order the development life cycle stages.",
        explanation: "Analysis → Design → Coding → Testing.",
        items: [
          { id: "design", text: "Design" },
          { id: "testing", text: "Testing" },
          { id: "analysis", text: "Analysis" },
          { id: "coding", text: "Coding" },
        ],
        correctOrder: ["analysis", "design", "coding", "testing"],
      },
      {
        id: "s5-t9",
        unitId: U,
        topicCode: "7.1",
        type: "mcq",
        difficulty: "core",
        prompt: "Abstraction is…",
        explanation: "Removing unnecessary detail to focus on the important parts.",
        choices: [
          { id: "a", text: "removing unnecessary detail to focus on what matters" },
          { id: "b", text: "breaking a problem into sub-problems", misconception: "that's decomposition, not abstraction." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t10",
        unitId: U,
        topicCode: "7.2",
        type: "mcq",
        difficulty: "core",
        prompt: "Which flowchart symbol represents a decision?",
        explanation: "A diamond, with two branches (yes/no).",
        choices: [
          { id: "a", text: "Diamond" },
          { id: "b", text: "Parallelogram", misconception: "a parallelogram is input/output." },
          { id: "c", text: "Rectangle", misconception: "a rectangle is a process." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t11",
        unitId: U,
        topicCode: "7.3",
        type: "mcq",
        difficulty: "core",
        prompt: "Which Cambridge pseudocode loop checks its condition at the END?",
        explanation: "REPEAT…UNTIL checks at the end, so it always runs at least once.",
        choices: [
          { id: "a", text: "REPEAT…UNTIL" },
          { id: "b", text: "WHILE…ENDWHILE", misconception: "WHILE checks at the start." },
          { id: "c", text: "FOR…NEXT", misconception: "FOR is count-controlled, not condition-at-end." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t12",
        unitId: U,
        topicCode: "7.3",
        type: "mcq",
        difficulty: "core",
        prompt: "Which is the correct Cambridge assignment?",
        explanation: "Cambridge uses ← for assignment.",
        choices: [
          { id: "a", text: "Count ← 0" },
          { id: "b", text: "Count == 0", misconception: "== is a comparison in some languages, not Cambridge assignment." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t13",
        unitId: U,
        topicCode: "7.4",
        type: "numeric",
        difficulty: "core",
        commandWord: "Calculate",
        prompt: "Total ← 0; FOR i ← 1 TO 5: Total ← Total + i. Final Total?",
        explanation: "1+2+3+4+5 = 15.",
        answer: 15,
      },
      {
        id: "s5-t14",
        unitId: U,
        topicCode: "7.4",
        type: "mcq",
        difficulty: "core",
        prompt: "Bubble sort works by…",
        explanation: "Comparing adjacent items and swapping if they're out of order, over repeated passes.",
        choices: [
          { id: "a", text: "comparing adjacent items and swapping out-of-order pairs" },
          { id: "b", text: "checking each item against a target", misconception: "that's linear search, not bubble sort." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t15",
        unitId: U,
        topicCode: "7.4",
        type: "mcq",
        difficulty: "core",
        prompt: "Which algorithm checks each item in turn until it finds the target?",
        explanation: "Linear search examines items one by one.",
        choices: [
          { id: "a", text: "Linear search" },
          { id: "b", text: "Bubble sort", misconception: "bubble sort orders a list; it doesn't search for a value." },
        ],
        correctId: "a",
      },
      {
        id: "s5-t16",
        unitId: U,
        topicCode: "7.7",
        type: "numeric",
        difficulty: "stretch",
        commandWord: "Calculate",
        prompt: "x ← 5; y ← 0; WHILE x > 0 DO: y ← y + x; x ← x − 1; ENDWHILE. Final y?",
        explanation: "5+4+3+2+1 = 15.",
        answer: 15,
      },
    ],
  },
  tutor: {
    conceptSummary:
      "Sector 5 covers algorithm design (Topic 7): the development life cycle (analysis with abstraction & decomposition → design with structure diagrams/flowcharts/pseudocode → coding → testing); flowchart symbols (terminator, process, input/output parallelogram, decision diamond, flow line); Cambridge pseudocode conventions (UPPERCASE, ← assignment, DECLARE, IF/CASE, FOR/WHILE/REPEAT, MOD/DIV, arrays, procedures/functions); standard algorithms (linear search, bubble sort comparing adjacent items, totalling, counting, max/min/average); validation (range/length/type/presence/format/check digit) vs verification (visual + double-entry); test data (normal/abnormal/extreme/boundary); and trace tables.",
    misconceptions: [
      "Validation vs verification — validation checks input is sensible; verification checks it was entered/copied accurately.",
      "Extreme vs boundary — extreme is one accepted edge value; boundary tests that edge AND its rejected neighbour.",
      "Off-by-one errors in loops and bubble-sort passes.",
      "Trace-table column errors and wrong assignment direction (← not =).",
    ],
  },
};
